/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import config.CRUD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Riqqi
 */
public final class MainMenu extends javax.swing.JFrame {

   /**
    * Creates new form MainMenu
    */
   CRUD crud;
   String namaAkun;
   int idAkun;
   ResultSet akun;
   String saldo;

   public MainMenu(int idAkun) {
      initComponents();
      crud = new CRUD();
      this.idAkun = idAkun;
      refreshSaldo();

      PanelPelanggan pelanggan = new PanelPelanggan(crud);
      pelanggan.setVisible(true);
      jTabbedPane1.addTab("PELANGGAN", pelanggan);

      PanelTransJual transJual = new PanelTransJual(idAkun, crud);
      transJual.setVisible(true);
      jTabbedPane1.addTab("JUAL PULSA", transJual);

      PanelsiSaldo transBeli = new PanelsiSaldo(idAkun, crud);
      transBeli.setVisible(true);
      jTabbedPane1.addTab("ISI SALDO", transBeli);

      PanelProfil profil = new PanelProfil(idAkun, crud);
      profil.setVisible(true);
      jTabbedPane1.addTab("PROFIL", profil);

   }

   public void refreshSaldo() {
      akun = crud.ambilData("SELECT * FROM  akun WHERE id_akun = '" + idAkun + "'");
      try {
         if (akun.next()) {
            saldo = crud.integerToRupiah(Integer.parseInt(akun.getString("saldo")));
            namaAkun = akun.getString("nama");
         }
         System.out.println("");
         lblAdmin.setText(namaAkun.toUpperCase());
      } catch (SQLException ex) {
         Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      lblAdmin = new javax.swing.JLabel();
      btnLogout = new javax.swing.JButton();
      jTabbedPane1 = new javax.swing.JTabbedPane();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setText("SISTEM INFORMASI PENJUALAN PULSA TOKO RISMA");

      lblAdmin.setText("Admin");

      btnLogout.setText("LOGOUT");
      btnLogout.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLogoutActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(374, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addGap(396, 396, 396))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addComponent(lblAdmin)
                  .addGap(18, 18, 18)
                  .addComponent(btnLogout)
                  .addContainerGap())))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnLogout)
               .addComponent(lblAdmin))
            .addGap(31, 31, 31))
      );

      jTabbedPane1.setToolTipText("");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jTabbedPane1)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents
// --MAIN MENU--
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      int con = JOptionPane.showConfirmDialog(this, "Yakin Ingin LOGOUT ?");
      switch (con) {
         case 0:
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
            break;
      }
    }//GEN-LAST:event_btnLogoutActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Windows".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new MainMenu(1).setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnLogout;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JTabbedPane jTabbedPane1;
   private javax.swing.JLabel lblAdmin;
   // End of variables declaration//GEN-END:variables
}
