/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import config.CRUD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Riqqi
 */
public class PanelPelanggan extends javax.swing.JPanel {

   /**
    * Creates new form PanelPelanggan
    */
   DefaultTableModel dt;
   boolean[] pelangganSuccess = new boolean[2];
   String namaLama;
   String plnLama;
   CRUD crud;

   public PanelPelanggan(CRUD crud) {
      initComponents();
      this.crud = crud;
      refreshTablePelanggan();
   }

   public void refreshTablePelanggan() {
      dt = (DefaultTableModel) tabelPelanggan.getModel();
      ResultSet pelanggan = crud.ambilData("SELECT * FROM pelanggan");
      try {
         int no = 1;
         dt.getDataVector().clear();
         dt.fireTableDataChanged();
         while (pelanggan.next()) {
            String noPln = pelanggan.getString("no_pln");
            String namaPelanggan = pelanggan.getString("nama");
            dt.addRow(new Object[]{no++, namaPelanggan, noPln});
         }
         tabelPelanggan.setModel(dt);
         reset();
      } catch (SQLException ex) {
         Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
      }
   }

   public void reset() {
      tNama.setText("");
      tNoPln.setText("");
      crud.defaultText(tNama, "Nama");
      crud.defaultText(tNoPln, "No PLN");
      tNama.requestFocus();
      Arrays.fill(pelangganSuccess, false);
      btnSimpan.setEnabled(false);
      btnBatal.setVisible(false);
      btnSimpan.setText("SIMPAN");
      tabelPelanggan.clearSelection();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel2 = new javax.swing.JLabel();
      tNama = new javax.swing.JTextField();
      tNoPln = new javax.swing.JTextField();
      btnReset = new javax.swing.JButton();
      btnSimpan = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      tabelPelanggan = new javax.swing.JTable();
      btnBatal = new javax.swing.JButton();

      jLabel2.setText("Input Pelanggan");

      tNama.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nama"));
      tNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
      tNama.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            tNamaFocusLost(evt);
         }
      });

      tNoPln.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "No PLN"));
      tNoPln.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
      tNoPln.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            tNoPlnFocusLost(evt);
         }
      });

      btnReset.setText("RESET");
      btnReset.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnResetActionPerformed(evt);
         }
      });

      btnSimpan.setText("SIMPAN");
      btnSimpan.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSimpanActionPerformed(evt);
         }
      });

      tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "No", "Nama", "No PLN"
         }
      ));
      tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tabelPelangganMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tabelPelanggan);

      btnBatal.setText("BATAL");
      btnBatal.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBatalActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel2)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(btnReset)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(btnSimpan))
                        .addComponent(tNoPln, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addGroup(layout.createSequentialGroup()
                  .addGap(57, 57, 57)
                  .addComponent(btnBatal)))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(436, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tNoPln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnReset)
               .addComponent(btnSimpan))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnBatal)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(176, 176, 176))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void tNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNamaFocusLost
      if (btnSimpan.getText().equals("SIMPAN")) {
         pelangganSuccess[0] = crud.ValidasiTextHarusDiIsi(tNama, "Nama", btnSimpan);
      } else if (btnSimpan.getText().equals("EDIT")) {
         pelangganSuccess[1] = true;
         pelangganSuccess[0] = crud.ValidasiTextHarusDiIsi(tNama, "Nama", btnSimpan);
         if (tNama.getText().equals(namaLama)) {
            pelangganSuccess[0] = true;
         }
         //         ini masih memperbolehkan nama sama dengan pelanggan lain
      }
      crud.validasiAND(pelangganSuccess, btnSimpan);
   }//GEN-LAST:event_tNamaFocusLost

   private void tNoPlnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNoPlnFocusLost
      if (btnSimpan.getText().equals("SIMPAN")) {
         pelangganSuccess[1] = crud.ValidasiTextHarusDiIsi(tNoPln, "No PLN", btnSimpan);
         if (pelangganSuccess[1]) {
            ResultSet pelanggan = crud.ambilData("SELECT * FROM pelanggan WHERE no_pln = '" + tNoPln.getText() + "'");
            pelangganSuccess[1] = crud.validasiDataSudahTerdaftar(tNoPln, "No PLN", pelanggan);
         }
      } else if (btnSimpan.getText().equals("EDIT")) {
         //         if (tNoPln.getText().equals(plnLama)) {
         //            success[1] = true;
         //         } else {
         //            ResultSet pelanggan = crud.ambilData("SELECT * FROM  pelanggan WHERE no_pln = '" + tNoPln.getText() + "'");
         //            success[1] = crud.validasiDataSudahTerdaftar(tNoPln, "No PLN", pelanggan);
         //         }
         pelangganSuccess[1] = true;
      }

      crud.validasiAND(pelangganSuccess, btnSimpan);
   }//GEN-LAST:event_tNoPlnFocusLost

   private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      if (btnSimpan.getText().equals("SIMPAN")) {
         reset();
      } else {
         reset();
         btnSimpan.setText("EDIT");
         tNama.setText(namaLama);
         tNoPln.setText(plnLama);
         btnBatal.setVisible(true);
      }
   }//GEN-LAST:event_btnResetActionPerformed

   private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      if (btnSimpan.getText().equals("SIMPAN")) {
         crud.insertData("INSERT INTO `pelanggan`(`no_pln`, `nama`) VALUES ('" + tNoPln.getText() + "','" + tNama.getText() + "')");
      } else {
         crud.updateData("UPDATE `pelanggan` SET `nama`='" + tNama.getText() + "' WHERE no_pln = '" + tNoPln.getText() + "'");
      }

      refreshTablePelanggan();
   }//GEN-LAST:event_btnSimpanActionPerformed

   private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
      crud.defaultText(tNama, "Nama");
      crud.defaultText(tNoPln, "No PLN");
      tNama.setText(tabelPelanggan.getValueAt(tabelPelanggan.getSelectedRow(), 1).toString());
      tNoPln.setText(tabelPelanggan.getValueAt(tabelPelanggan.getSelectedRow(), 2).toString());
      namaLama = tNama.getText();
      plnLama = tNoPln.getText();
      btnSimpan.setText("EDIT");
      btnBatal.setVisible(true);
      tNoPln.setEditable(false);
   }//GEN-LAST:event_tabelPelangganMouseClicked

   private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
      reset();
      tNoPln.setEditable(true);
   }//GEN-LAST:event_btnBatalActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnBatal;
   private javax.swing.JButton btnReset;
   private javax.swing.JButton btnSimpan;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextField tNama;
   private javax.swing.JTextField tNoPln;
   private javax.swing.JTable tabelPelanggan;
   // End of variables declaration//GEN-END:variables
}
