/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import config.CRUD;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author windows
 */
public class PanelProfil extends javax.swing.JPanel {

   int idAkun;
   CRUD crud;
   String namaLama;
   String noHPLama;
   String alamatLama;
   String passLama;
   boolean[] success = new boolean[4];

   /**
    * Creates new form profilku
    */
   public PanelProfil(int idAkun, CRUD crud) {
      this.idAkun = idAkun;
      this.crud = crud;
      initComponents();
      isiForm();

   }

   public void isiForm() {
      try {
         ResultSet akun = crud.ambilData("SELECT * FROM akun WHERE id_akun = '" + idAkun + "'");
         if (akun.first()) {
            namaLama = akun.getString("nama");
            noHPLama = akun.getString("no_hp");
            alamatLama = akun.getString("alamat");
            passLama = crud.StringToMD5(akun.getString("password"));

            tNama.setText(namaLama);
            tNoHp.setText(noHPLama);
            tAlamat.setText(alamatLama);
            tPassword.setText(passLama);
         }
      } catch (SQLException | NoSuchAlgorithmException ex) {
         Logger.getLogger(PanelProfil.class.getName()).log(Level.SEVERE, null, ex);
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      tNama = new javax.swing.JTextField();
      tNoHp = new javax.swing.JTextField();
      tAlamat = new javax.swing.JTextField();
      tPassword = new javax.swing.JPasswordField();
      chkSee = new javax.swing.JCheckBox();
      btnSimpan = new javax.swing.JButton();
      lblSaldo = new javax.swing.JLabel();
      btnBatal = new javax.swing.JButton();

      addComponentListener(new java.awt.event.ComponentAdapter() {
         public void componentShown(java.awt.event.ComponentEvent evt) {
            formComponentShown(evt);
         }
      });

      tNama.setBorder(javax.swing.BorderFactory.createTitledBorder("Nama"));

      tNoHp.setBorder(javax.swing.BorderFactory.createTitledBorder("No Hp"));

      tAlamat.setBorder(javax.swing.BorderFactory.createTitledBorder("Alamat"));

      tPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

      chkSee.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            chkSeeActionPerformed(evt);
         }
      });

      btnSimpan.setText("Simpan");

      lblSaldo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
      lblSaldo.setText("Saldo : Rp");

      btnBatal.setText("Batal");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(tNoHp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(tNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(btnSimpan)
                     .addComponent(btnBatal)
                     .addComponent(chkSee)
                     .addComponent(lblSaldo)))
               .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(lblSaldo)
                  .addGap(18, 18, 18)
                  .addComponent(btnSimpan))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(tNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnBatal))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(chkSee)
                  .addGap(10, 10, 10)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      crud.refreshSaldo(idAkun, lblSaldo);
      isiForm();
   }//GEN-LAST:event_formComponentShown

   private void chkSeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSeeActionPerformed
      crud.togglePassword(tPassword, chkSee);
   }//GEN-LAST:event_chkSeeActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnBatal;
   private javax.swing.JButton btnSimpan;
   private javax.swing.JCheckBox chkSee;
   private javax.swing.JLabel lblSaldo;
   private javax.swing.JTextField tAlamat;
   private javax.swing.JTextField tNama;
   private javax.swing.JTextField tNoHp;
   private javax.swing.JPasswordField tPassword;
   // End of variables declaration//GEN-END:variables
}
