/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import config.CRUD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMMARA KHAIRUNNISA
 */
public class PanelsiSaldo extends javax.swing.JPanel {

   int idAkun;
   CRUD crud;
   long nominal;
   DefaultTableModel dt;
   DefaultComboBoxModel<String> cb;

   /**
    * Creates new form isi_saldo
    */
   public PanelsiSaldo(int idAkun, CRUD crud) {
      this.idAkun = idAkun;
      this.crud = crud;
      initComponents();
      crud.refreshSaldo(idAkun, lblSaldo);
      refreshTableTransBeli();
   }

   public void refreshTableTransBeli() {
      dt = (DefaultTableModel) tabelTransBeli.getModel();
      ResultSet transBeli = crud.ambilData("SELECT trans_beli.`no_trans_beli`, trans_beli.`nominal`, trans_beli.`id_akun`, trans_beli.`tgl`, akun.nama AS admin FROM `trans_beli` INNER JOIN akun ON trans_beli.id_akun = akun.id_akun WHERE trans_beli.id_akun = " + idAkun + " ORDER BY tgl;");
      System.out.println("function refresh tabel trans beli dijalankan");
      try {
         int no = 1;
         dt.getDataVector().clear();
         dt.fireTableDataChanged();
         while (transBeli.next()) {
            String tglOke = crud.dateToTgl(transBeli.getString("tgl"));

            String nominal = crud.integerToRupiah(Integer.parseInt(transBeli.getString("nominal")));
            String admin = transBeli.getString("admin");
            dt.addRow(new Object[]{no++, tglOke, nominal, admin});
         }
         tabelTransBeli.setModel(dt);
      } catch (SQLException ex) {
         Logger.getLogger(PanelTransJual.class.getName()).log(Level.SEVERE, null, ex);
      }
   }

   public void insertListNominal() {
      ResultSet nominal = crud.ambilData("SELECT * FROM saldo");
      cb = new DefaultComboBoxModel<String>();
      try {
         cb.addElement("---pilih---");
         while (nominal.next()) {
            String nominalRp = crud.integerToRupiah(Integer.parseInt(nominal.getString("nominal")));
            cb.addElement(nominalRp);
         }
         cbNominal.setModel(cb);
      } catch (SQLException ex) {
         Logger.getLogger(PanelTransJual.class.getName()).log(Level.SEVERE, null, ex);
      }
   }

   public void reset() {
      btnIsi.setEnabled(false);
      cbNominal.setSelectedIndex(0);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      btnIsi = new javax.swing.JButton();
      cbNominal = new javax.swing.JComboBox();
      jScrollPane1 = new javax.swing.JScrollPane();
      tabelTransBeli = new javax.swing.JTable();
      lblSaldo = new javax.swing.JLabel();
      btnReset = new javax.swing.JButton();

      addComponentListener(new java.awt.event.ComponentAdapter() {
         public void componentShown(java.awt.event.ComponentEvent evt) {
            formComponentShown(evt);
         }
      });

      btnIsi.setText("ISI");
      btnIsi.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnIsiActionPerformed(evt);
         }
      });

      cbNominal.setBorder(javax.swing.BorderFactory.createTitledBorder("Nominal"));
      cbNominal.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbNominalActionPerformed(evt);
         }
      });

      tabelTransBeli.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "No", "Tgl", "Nominal", "Akun"
         }
      ));
      jScrollPane1.setViewportView(tabelTransBeli);

      lblSaldo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
      lblSaldo.setText("Saldo : Rp--");

      btnReset.setText("RESET");
      btnReset.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnResetActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(cbNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIsi))
                     .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnReset)))
                  .addGap(18, 18, 18)
                  .addComponent(lblSaldo)))
            .addContainerGap(35, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(cbNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(btnIsi)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnReset))
               .addGroup(layout.createSequentialGroup()
                  .addGap(20, 20, 20)
                  .addComponent(lblSaldo)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
            .addGap(22, 22, 22))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      refreshTableTransBeli();
      crud.refreshSaldo(idAkun, lblSaldo);
      insertListNominal();
   }//GEN-LAST:event_formComponentShown

   private void cbNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNominalActionPerformed
      if (cbNominal.getSelectedIndex() == 0) {
         crud.comboDefault(cbNominal, "Nominal");
         btnIsi.setEnabled(false);
      } else {
         crud.comboSuccess(cbNominal, "Nominal");
         nominal = (long) crud.rupiahToNumber(cbNominal.getSelectedItem().toString());
         btnIsi.setEnabled(true);
      }
   }//GEN-LAST:event_cbNominalActionPerformed

   private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      reset();
   }//GEN-LAST:event_btnResetActionPerformed

   private void btnIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsiActionPerformed
      crud.insertData("INSERT INTO `trans_beli`( `nominal`, `id_akun`) VALUES ('" + nominal + "','" + idAkun + "')");
      refreshTableTransBeli();
      reset();
      crud.refreshSaldo(idAkun, lblSaldo);
   }//GEN-LAST:event_btnIsiActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnIsi;
   private javax.swing.JButton btnReset;
   private javax.swing.JComboBox cbNominal;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JLabel lblSaldo;
   private javax.swing.JTable tabelTransBeli;
   // End of variables declaration//GEN-END:variables
}
